version: 0.2

phases:
  install:
    runtime-version:
      python: 3.8
    commands:
      - pip3 install pytest

  pre_build:
    commands:
      - echo "Pre build phase.."
      - pytest --junit.xml ./junit.xml

  build:
    commands:
      - echo "Build phase.."
      - sam build


  post_build:
    commands:
      - echo "Post build phase.."

reports:
  arn:aws:codebuild:$AWS_REGION:$ACCOUNT_ID:report-group/r-u-phishing-backend-report-group:
    files:
      - ./junit.xml

artifacts:
  files:
    -