AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
#  MyApi:
#    Type: AWS::Serverless::Api
#    Properties:
#      StageName: Prod
#      Auth:
#        DefaultAuthorizer: MyLambdaTokenAuthorizer
#        Authorizers:
#          MyLambdaTokenAuthorizer:
#            FunctionArn: !GetAtt RUPhishingBackendLambdaFunction.Arn
#  https://docs.aws.amazon.com/ko_kr/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-methodsettings
  RUPhishingBackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
      MethodSettings:
        - ResourcePath: /
          HttpMethod: GET
          CachingEnabled: true
          CacheTtlInSeconds: 300
  RUPhishingBackendLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: wsi-api-function
      Events:
        EventApi:
          Type: Api
          Properties:
            Path: /test
            Method: get
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile


Outputs:
  RUPhishingBackendLambdaFunction:
    Description: "R-U-Phishing Backend Lambda Function ARN"
    Value: !GetAtt RUPhishingBackendLambdaFunction.Arn