AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  RUPhishingBackendLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: wsi-api-function
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /hello-world
            Method: get
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile


Outputs:
  RUPhishingBackendLambdaFunction:
    Description: "R-U-Phishing Backend Lambda Function ARN"
    Value: !GetAtt RUPhishingBackendLambdaFunction.Arn